<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MataKuliah;


class MatakuliahSeeder extends Seeder
{
    public function run()
    {
        // Create an admin user
        MataKuliah::insert([
            //Semester 1
            [
                'kode_mk' => 'PAIK6102',
                'nama' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 7,
                'dosen_id_2' => 6,
                'dosen_id_3' => 17,
            ],
            [
                'kode_mk' => 'PAIK6101',
                'nama' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 22,
                'dosen_id_2' => 10,
                'dosen_id_3' => 15,
            ],
            [
                'kode_mk' => 'PAIK6104',
                'nama' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 29,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6105',
                'nama' => 'Aljabar Liniier',
                'sks' => 3,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 7,
                'dosen_id_2' => 3,
                'dosen_id_3' => 20,
            ],
            [
                'kode_mk' => 'PAIK6103',
                'nama' => 'Struktur Diskrit',
                'sks' => 4,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 3,
                'dosen_id_2' => 19,
                'dosen_id_3' => 28,
            ],
            [
                'kode_mk' => 'PAIK6107',
                'nama' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 22,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6004',
                'nama' => 'Bahasa Indonesia',
                'sks' => 2,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 25,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'UUW00005',
                'nama' => 'Olahraga',
                'sks' => 2,
                'semester' => 1,
                'jenis' => 'Wajib',
                'kuota' => 45,
                'dosen_id' => 25,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],

            // Semester 2
            [
                'kode_mk' => 'PAIK6201',
                'nama' => 'Matematika II',
                'sks' => 2,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 28,
                'dosen_id_2' => 29,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6202',
                'nama' => 'Algoritma dan Pemrograman',
                'sks' => 4,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 8,
                'dosen_id_2' => 11,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6203',
                'nama' => 'Organisasi dan Arsitektur Komputer',
                'sks' => 3,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 22,
                'dosen_id_2' => 10,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6204',
                'nama' => 'Aljabar Linier',
                'sks' => 3,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 12,
                'dosen_id_2' => 29,
                'dosen_id_3' => 5,
            ],
            [
                'kode_mk' => 'UUW00004',
                'nama' => 'Bahasa Indonesia',
                'sks' => 2,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 22,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'UUW00006',
                'nama' => 'Internet of Things (IoT)',
                'sks' => 2,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 12,
                'dosen_id_2' => 16,
                'dosen_id_3' => 27,
            ],
            [
                'kode_mk' => 'UUW00011',
                'nama' => 'Pendidikan Agama Islam',
                'sks' => 2,
                'semester' => 2,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 18,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],

            // Semester 3
            [
                'kode_mk' => 'PAIK6301',
                'nama' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 30,
                'dosen_id_2' => 14,
                'dosen_id_3' => 17,
            ],
            [
                'kode_mk' => 'PAIK6303',
                'nama' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 13,
                'dosen_id_2' => 23,
                'dosen_id_3' => 30,
            ],
            [
                'kode_mk' => 'PAIK6302',
                'nama' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 21,
                'dosen_id_2' => 11,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6305',
                'nama' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 11,
                'dosen_id_2' => 8,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6304',
                'nama' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 12,
                'dosen_id_2' => 19,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6306',
                'nama' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 4,
                'dosen_id_2' => 5,
                'dosen_id_3' => null,
            ],

            // Semester 4
            [
                'kode_mk' => 'PAIK6401',
                'nama' => 'Pemrograman Berorientasi Objek',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 14,
                'dosen_id_2' => 17,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6402',
                'nama' => 'Jaringan Komputer',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 15,
                'dosen_id_2' => 16,
                'dosen_id_3' => 18,
            ],
            [
                'kode_mk' => 'PAIK6403',
                'nama' => 'Manajemen Basis Data',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 14,
                'dosen_id_2' => 13,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6404',
                'nama' => 'Grafika dan Komputasi Visual',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 3,
                'dosen_id_2' => 7,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6405',
                'nama' => 'Rekayasa Perangkat Lunak',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 9,
                'dosen_id_2' => 23,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6406',
                'nama' => 'Sistem Cerdas',
                'sks' => 3,
                'semester' => 4,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 4,
                'dosen_id_2' => 7,
                'dosen_id_3' => null,
            ],

            // Semester 5
            [
                'kode_mk' => 'PAIK6501',
                'nama' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 4,
                'dosen_id_2' => 26,
                'dosen_id_3' => 29,
            ],
            [
                'kode_mk' => 'PAIK6502',
                'nama' => 'Komputasi Tersebar Paralel',
                'sks' => 3,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 15,
                'dosen_id_2' => 26,
                'dosen_id_3' => 6,
            ],
            [
                'kode_mk' => 'PAIK6503',
                'nama' => 'Sistem Informasi',
                'sks' => 4,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 4,
                'dosen_id_2' => 26,
                'dosen_id_3' => 29,
            ],
            [
                'kode_mk' => 'PAIK6504',
                'nama' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 8,
                'dosen_id_2' => 9,
                'dosen_id_3' => 27,
            ],
            [
                'kode_mk' => 'PAIK6505',
                'nama' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 5,
                'dosen_id_2' => 22,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6506',
                'nama' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 15,
                'dosen_id_2' => 27,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'UUW00008',
                'nama' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => 5,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 9,
                'dosen_id_2' => 20,
                'dosen_id_3' => 23,
            ],

            // Semester 6
            [
                'kode_mk' => 'PAIK6601',
                'nama' => 'Analisis dan Strategi Algoritma',
                'sks' => 3,
                'semester' => 6,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 4,
                'dosen_id_2' => 6,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6602',
                'nama' => 'Uji Perangkat Lunak',
                'sks' => 3,
                'semester' => 6,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 19,
                'dosen_id_2' => 26,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6603',
                'nama' => 'Masyarakat dan Etika Profesi',
                'sks' => 3,
                'semester' => 6,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 20,
                'dosen_id_2' => 12,
                'dosen_id_3' => 18,
            ],
            [
                'kode_mk' => 'PAIK6604',
                'nama' => 'Praktik Kerja Lapangan',
                'sks' => 3,
                'semester' => 6,
                'jenis' => 'Wajib',
                'kuota' => 250,
                'dosen_id' => 4,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6605',
                'nama' => 'Manajemen Proyek',
                'sks' => 3,
                'semester' => 6,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 13,
                'dosen_id_2' => 8,
                'dosen_id_3' => null,
            ],

            // Semester 7
            [
                'kode_mk' => 'PAIK6701',
                'nama' => 'Metodologi Penelitian dan Penulisan Ilmiah',
                'sks' => 2,
                'semester' => 7,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 5,
                'dosen_id_2' => 20,
                'dosen_id_3' => 6,
            ],
            [
                'kode_mk' => 'PAIK6702',
                'nama' => 'Teori Bahasa dan Otomata',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Wajib',
                'kuota' => 50,
                'dosen_id' => 28,
                'dosen_id_2' => 29,
                'dosen_id_3' => 12,
            ],
            [
                'kode_mk' => 'PAIK6703',
                'nama' => 'Metode Perangkat Lunak',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 9,
                'dosen_id_2' => 14,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6704',
                'nama' => 'Kualitas Perangkat Lunak',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 9,
                'dosen_id_2' => 26,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6705',
                'nama' => 'Pemodelan dan Simulasi',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 15,
                'dosen_id_2' => 30,
                'dosen_id_3' => 20,
            ],
            [
                'kode_mk' => 'PAIK6706',
                'nama' => 'Visi Komputer',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 3,
                'dosen_id_2' => 6,
                'dosen_id_3' => 11,
            ],
            [
                'kode_mk' => 'PAIK6707',
                'nama' => 'Audit Sistem Informasi',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 45,
                'dosen_id' => 13,
                'dosen_id_2' => 8,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6708',
                'nama' => 'Penambangan Data',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 16,
                'dosen_id_2' => 19,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6709',
                'nama' => 'Sistem Tertanam',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 16,
                'dosen_id_2' => 23,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6710',
                'nama' => 'Algoritma Evolusioner',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 10,
                'dosen_id_2' => 22,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6711',
                'nama' => 'Komputasi Lunak',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 50,
                'dosen_id' => 10,
                'dosen_id_2' => 12,
                'dosen_id_3' => 17,
            ],
            [
                'kode_mk' => 'PAIK6712',
                'nama' => 'Temu Balik Informasi',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Pilihan',
                'kuota' => 45,
                'dosen_id' => 5,
                'dosen_id_2' => 4,
                'dosen_id_3' => null,
            ],

            // Semester 8
            [
                'kode_mk' => 'PAIK6801',
                'nama' => 'Topik Khusus RPL & STI',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 8,
                'dosen_id_2' => 19,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6802',
                'nama' => 'Topik Khusus SC & KG',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 7,
                'dosen_id_2' => 10,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6803',
                'nama' => 'Evolusi Perangkat Lunak',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 27,
                'dosen_id_2' => 14,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6804',
                'nama' => 'Rekayasa Sistem',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 8,
                'dosen_id_2' => 26,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6805',
                'nama' => 'Komputasi Awan',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 26,
                'dosen_id_2' => 27,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6806',
                'nama' => 'Arsitektur Perangkat Lunak',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 27,
                'dosen_id_2' => 14,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6807',
                'nama' => 'Pemrograman Lanjut',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 14,
                'dosen_id_2' => 26,
                'dosen_id_3' => 6,
            ],
            [
                'kode_mk' => 'PAIK6808',
                'nama' => 'Pengenalan Pola',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 11,
                'dosen_id_2' => 3,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6809',
                'nama' => 'Kriptografi',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 15,
                'dosen_id_2' => 20,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'PAIK6810',
                'nama' => 'Bioinformatika',
                'sks' => 3,
                'semester' => 8,
                'jenis' => 'Pilihan',
                'kuota' => 30,
                'dosen_id' => 6,
                'dosen_id_2' => 17,
                'dosen_id_3' => null,
            ],

            [
                'kode_mk' => 'PAIK6821',
                'nama' => 'Tugas Akhir',
                'sks' => 6,
                'semester' => 8,
                'jenis' => 'Wajib',
                'kuota' => 250,
                'dosen_id' => 19,
                'dosen_id_2' => null,
                'dosen_id_3' => null,
            ],
            [
                'kode_mk' => 'UUW00009',
                'nama' => 'Kuliah Kerja Nyata (KKN)',
                'sks' => 3,
                'semester' => 7,
                'jenis' => 'Wajib',
                'kuota' => 250,
                'dosen_id' => 23,
                'dosen_id_2' => 22,
                'dosen_id_3' => null,
            ],
        ]);
    }
}